version: '3'
services:

  dbapi:
    build: .
    ports:
      - 9000:9000
    links:
      - mongodb
    depends_on:
      - mongodb
    environment:
      - "TZ=Asia/Tokyo"
    command: app -dbaddr=mongodb -addr=:9000
  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - mongodata
    environment:
      - "TZ=Asia/Tokyo"
volumes:
  mongodata:
    driver: local
