# The unit of this parameter is minute
duration: 1

# The address of the sensor API
sensor: http://localhost:5000/api/v1/sensors

# The address of the DB API
db: http://localhost:9000/sensors
